### ISSUE TITLE
Publish on Maven repository

### ISSUE THREAD

**Issue by javydreamercsw** [ForOhForError/ScryfallAPIBinding#1]
Would be nice to have this available to use as a dependency.

**Comment by javydreamercsw** [comment]
Please complete the following steps in order to being able to publish artifacts: https://central.sonatype.org/pages/ossrh-guide.html

**Comment by ForOhForError** [comment]
For the moment, please use https://jitpack.io/ if desired.

**Comment by ForOhForError** [comment]
Published.

Group id io.github.forohforerror
Artifact ID ScryfallAPIBinding
Starts with version 1.9.1
